from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 581)
        MainWindow.setMinimumSize(QtCore.QSize(940, 560))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(parent=self.widget_4)
        self.widget.setMinimumSize(QtCore.QSize(0, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toggleButton = QtWidgets.QPushButton(parent=self.widget)
        self.toggleButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../icons/header/bars-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toggleButton.setIcon(icon)
        self.toggleButton.setIconSize(QtCore.QSize(20, 20))
        self.toggleButton.setCheckable(True)
        self.toggleButton.setAutoExclusive(True)
        self.toggleButton.setObjectName("toggleButton")
        self.horizontalLayout_3.addWidget(self.toggleButton)
        spacerItem = QtWidgets.QSpacerItem(387, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 9, -1)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchInput = QtWidgets.QLineEdit(parent=self.widget)
        self.searchInput.setMinimumSize(QtCore.QSize(400, 30))
        self.searchInput.setObjectName("searchInput")
        self.horizontalLayout_2.addWidget(self.searchInput)
        self.searchButton = QtWidgets.QPushButton(parent=self.widget)
        self.searchButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\../icons/header/magnifying-glass-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.searchButton.setIcon(icon1)
        self.searchButton.setIconSize(QtCore.QSize(20, 20))
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_2.addWidget(self.searchButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(387, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.userButton = QtWidgets.QPushButton(parent=self.widget)
        self.userButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui\\../icons/header/user-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.userButton.setIcon(icon2)
        self.userButton.setIconSize(QtCore.QSize(20, 20))
        self.userButton.setObjectName("userButton")
        self.horizontalLayout_3.addWidget(self.userButton)
        self.verticalLayout_5.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget_4)
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.homePage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.homePage)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.homePage)
        self.tvshowsPage = QtWidgets.QWidget()
        self.tvshowsPage.setObjectName("tvshowsPage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tvshowsPage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.tvshowsPage)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.tvshowsPage)
        self.moviesPage = QtWidgets.QWidget()
        self.moviesPage.setObjectName("moviesPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.moviesPage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(parent=self.moviesPage)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.moviesPage)
        self.rankPage = QtWidgets.QWidget()
        self.rankPage.setObjectName("rankPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.rankPage)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_6 = QtWidgets.QLabel(parent=self.rankPage)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignTop)
        self.stackedWidget.addWidget(self.rankPage)
        self.userPage = QtWidgets.QWidget()
        self.userPage.setObjectName("userPage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.userPage)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_7 = QtWidgets.QLabel(parent=self.userPage)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.userPage)
        self.searchPage = QtWidgets.QWidget()
        self.searchPage.setObjectName("searchPage")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.searchPage)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_8 = QtWidgets.QLabel(parent=self.searchPage)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.searchPage)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_4, 0, 1, 1, 1)
        self.leftMenu = QtWidgets.QWidget(parent=self.centralwidget)
        self.leftMenu.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftMenu.sizePolicy().hasHeightForWidth())
        self.leftMenu.setSizePolicy(sizePolicy)
        self.leftMenu.setMinimumSize(QtCore.QSize(50, 0))
        self.leftMenu.setMaximumSize(QtCore.QSize(150, 16777215))
        self.leftMenu.setObjectName("leftMenu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftMenu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logoLabel_1 = QtWidgets.QLabel(parent=self.leftMenu)
        self.logoLabel_1.setEnabled(True)
        self.logoLabel_1.setMinimumSize(QtCore.QSize(50, 50))
        self.logoLabel_1.setMaximumSize(QtCore.QSize(50, 50))
        self.logoLabel_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.logoLabel_1.setText("")
        self.logoLabel_1.setPixmap(QtGui.QPixmap("ui\\../icons/sidebar/Crunchyroll_Logo.png"))
        self.logoLabel_1.setScaledContents(True)
        self.logoLabel_1.setObjectName("logoLabel_1")
        self.horizontalLayout.addWidget(self.logoLabel_1)
        self.logoLabel_3 = QtWidgets.QLabel(parent=self.leftMenu)
        self.logoLabel_3.setMinimumSize(QtCore.QSize(100, 36))
        self.logoLabel_3.setMaximumSize(QtCore.QSize(100, 36))
        self.logoLabel_3.setText("")
        self.logoLabel_3.setPixmap(QtGui.QPixmap("ui\\../icons/sidebar/crunchyroll_text.png"))
        self.logoLabel_3.setScaledContents(True)
        self.logoLabel_3.setObjectName("logoLabel_3")
        self.horizontalLayout.addWidget(self.logoLabel_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.frame = QtWidgets.QFrame(parent=self.leftMenu)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.homeButton_1 = QtWidgets.QToolButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeButton_1.sizePolicy().hasHeightForWidth())
        self.homeButton_1.setSizePolicy(sizePolicy)
        self.homeButton_1.setMinimumSize(QtCore.QSize(0, 45))
        self.homeButton_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui\\sidebar/house-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.homeButton_1.setIcon(icon3)
        self.homeButton_1.setIconSize(QtCore.QSize(20, 20))
        self.homeButton_1.setCheckable(True)
        self.homeButton_1.setAutoExclusive(True)
        self.homeButton_1.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.homeButton_1.setObjectName("homeButton_1")
        self.verticalLayout.addWidget(self.homeButton_1)
        self.tvshowsButton_1 = QtWidgets.QToolButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tvshowsButton_1.sizePolicy().hasHeightForWidth())
        self.tvshowsButton_1.setSizePolicy(sizePolicy)
        self.tvshowsButton_1.setMinimumSize(QtCore.QSize(0, 45))
        self.tvshowsButton_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ui\\../icons/sidebar/tv-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tvshowsButton_1.setIcon(icon4)
        self.tvshowsButton_1.setIconSize(QtCore.QSize(20, 20))
        self.tvshowsButton_1.setCheckable(True)
        self.tvshowsButton_1.setAutoExclusive(True)
        self.tvshowsButton_1.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.tvshowsButton_1.setObjectName("tvshowsButton_1")
        self.verticalLayout.addWidget(self.tvshowsButton_1)
        self.moviesButton_1 = QtWidgets.QToolButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moviesButton_1.sizePolicy().hasHeightForWidth())
        self.moviesButton_1.setSizePolicy(sizePolicy)
        self.moviesButton_1.setMinimumSize(QtCore.QSize(0, 45))
        self.moviesButton_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ui\\../icons/sidebar/film-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.moviesButton_1.setIcon(icon5)
        self.moviesButton_1.setIconSize(QtCore.QSize(20, 20))
        self.moviesButton_1.setCheckable(True)
        self.moviesButton_1.setAutoExclusive(True)
        self.moviesButton_1.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.moviesButton_1.setObjectName("moviesButton_1")
        self.verticalLayout.addWidget(self.moviesButton_1)
        self.rankButton_1 = QtWidgets.QToolButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rankButton_1.sizePolicy().hasHeightForWidth())
        self.rankButton_1.setSizePolicy(sizePolicy)
        self.rankButton_1.setMinimumSize(QtCore.QSize(0, 45))
        self.rankButton_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ui\\../icons/sidebar/ranking-star-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rankButton_1.setIcon(icon6)
        self.rankButton_1.setIconSize(QtCore.QSize(20, 20))
        self.rankButton_1.setCheckable(True)
        self.rankButton_1.setAutoExclusive(True)
        self.rankButton_1.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.rankButton_1.setObjectName("rankButton_1")
        self.verticalLayout.addWidget(self.rankButton_1)
        self.verticalLayout_3.addWidget(self.frame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 574, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.frame_2 = QtWidgets.QFrame(parent=self.leftMenu)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.exitButton_1 = QtWidgets.QToolButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton_1.sizePolicy().hasHeightForWidth())
        self.exitButton_1.setSizePolicy(sizePolicy)
        self.exitButton_1.setMinimumSize(QtCore.QSize(0, 45))
        self.exitButton_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ui\\../icons/sidebar/right-from-bracket-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.exitButton_1.setIcon(icon7)
        self.exitButton_1.setIconSize(QtCore.QSize(20, 20))
        self.exitButton_1.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.exitButton_1.setObjectName("exitButton_1")
        self.verticalLayout_2.addWidget(self.exitButton_1)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.leftMenu, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchInput.setPlaceholderText(_translate("MainWindow", "Search anime..."))
        self.label_3.setText(_translate("MainWindow", "Home Page"))
        self.label_4.setText(_translate("MainWindow", "TV Shows Page"))
        self.label_5.setText(_translate("MainWindow", "Movies Page"))
        self.label_6.setText(_translate("MainWindow", "Ranking Page"))
        self.label_7.setText(_translate("MainWindow", "User Page"))
        self.label_8.setText(_translate("MainWindow", "Search Page"))
        self.homeButton_1.setText(_translate("MainWindow", "       HOME"))
        self.tvshowsButton_1.setText(_translate("MainWindow", "       TV SHOWS"))
        self.moviesButton_1.setText(_translate("MainWindow", "       MOVIES"))
        self.rankButton_1.setText(_translate("MainWindow", "       RANKINGS"))
        self.exitButton_1.setText(_translate("MainWindow", "       EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())